In [54]:
import pandas as pd

path = 'C:/Users/julia/PycharmProjects/gnn-for-ppi/final_results/BRCA/ChebNet'


Split0_outer_ext = pd.read_csv(path+'/Split_0/results_outer_extended.csv')
Split1_outer_ext = pd.read_csv(path+'/Split_1/results_outer_extended.csv')
Split2_outer_ext = pd.read_csv(path+'/Split_2/results_outer_extended.csv')
Split3_outer_ext = pd.read_csv(path+'/Split_3/results_outer_extended.csv')
Split4_outer_ext = pd.read_csv(path+'/Split_4/results_outer_extended.csv')
Split5_outer_ext = pd.read_csv(path+'/Split_5/results_outer_extended.csv')
Split6_outer_ext = pd.read_csv(path+'/Split_6/results_outer_extended.csv')
Split7_outer_ext = pd.read_csv(path+'/Split_7/results_outer_extended.csv')
Split8_outer_ext = pd.read_csv(path+'/Split_8/results_outer_extended.csv')
Split9_outer_ext = pd.read_csv(path+'/Split_9/results_outer_extended.csv')

Split0_inner_ext = pd.read_csv(path+'/Split_0/results_inner_extended.csv')
Split1_inner_ext = pd.read_csv(path+'/Split_1/results_inner_extended.csv')
Split2_inner_ext = pd.read_csv(path+'/Split_2/results_inner_extended.csv')
Split3_inner_ext = pd.read_csv(path+'/Split_3/results_inner_extended.csv')
Split4_inner_ext = pd.read_csv(path+'/Split_4/results_inner_extended.csv')
Split5_inner_ext = pd.read_csv(path+'/Split_5/results_inner_extended.csv')
Split6_inner_ext = pd.read_csv(path+'/Split_6/results_inner_extended.csv')
Split7_inner_ext = pd.read_csv(path+'/Split_7/results_inner_extended.csv')
Split8_inner_ext = pd.read_csv(path+'/Split_8/results_inner_extended.csv')
Split9_inner_ext = pd.read_csv(path+'/Split_9/results_inner_extended.csv')

Split0_outer_av = pd.read_csv(path+'/Split_0/results_outer_average_over_folds.csv')
Split1_outer_av = pd.read_csv(path+'/Split_1/results_outer_average_over_folds.csv')
Split2_outer_av = pd.read_csv(path+'/Split_2/results_outer_average_over_folds.csv')
Split3_outer_av = pd.read_csv(path+'/Split_3/results_outer_average_over_folds.csv')
Split4_outer_av = pd.read_csv(path+'/Split_4/results_outer_average_over_folds.csv')
Split5_outer_av = pd.read_csv(path+'/Split_5/results_outer_average_over_folds.csv')
Split6_outer_av = pd.read_csv(path+'/Split_6/results_outer_average_over_folds.csv')
Split7_outer_av = pd.read_csv(path+'/Split_7/results_outer_average_over_folds.csv')
Split8_outer_av = pd.read_csv(path+'/Split_8/results_outer_average_over_folds.csv')
Split9_outer_av = pd.read_csv(path+'/Split_9/results_outer_average_over_folds.csv')

In [55]:
Overall_outer_ext = pd.concat([Split0_outer_ext, Split1_outer_ext,
                               Split2_outer_ext, Split3_outer_ext,
                               Split4_outer_ext, Split5_outer_ext,
                               Split6_outer_ext, Split7_outer_ext,
                               Split8_outer_ext, Split9_outer_ext]).reset_index(drop=True)

In [56]:
Overall_outer_ext

,outer_es_loss,outer_es_accuracy,test_loss,test_accuracy,number_epochs,timestamp,checkpoint_dir_name,done,training_iteration,trial_id,...,test_recall,test_specificity,test_f1_score,test_mcc,test_auroc,test_auprc,test_true_positives,test_false_negatives,test_false_positives,test_true_negatives
0,0.243571,0.909910,0.281586,0.869565,884,1777723271,NaN,False,1,a823e_00000,...,0.930556,0.803030,0.881579,0.742387,0.949074,0.949767,53.0,13.0,5.0,67.0
1,0.311020,0.836364,0.340615,0.862319,956,1777723504,NaN,False,1,a823e_00001,...,0.958333,0.757576,0.878981,0.735273,0.928241,0.906331,50.0,16.0,3.0,69.0
2,0.292369,0.872727,0.311006,0.876812,1559,1777725299,NaN,False,1,a823e_00002,...,0.944444,0.803030,0.888889,0.758324,0.934764,0.932651,53.0,13.0,4.0,68.0
3,0.276948,0.890909,0.287746,0.862319,1076,1777723882,NaN,False,1,a823e_00003,...,0.916667,0.803030,0.874172,0.726689,0.948232,0.947114,53.0,13.0,6.0,66.0
4,0.278245,0.890909,0.287042,0.876812,1023,1777726676,NaN,False,1,a823e_00004,...,0.944444,0.803030,0.888889,0.758324,0.948232,0.944712,53.0,13.0,4.0,68.0
5,0.243211,0.882883,0.333848,0.818841,747,1778446731,NaN,False,1,0b282_00000,...,0.805556,0.833333,0.822695,0.638285,0.933712,0.927569,55.0,11.0,14.0,58.0
6,0.284609,0.900000,0.309513,0.862319,1556,1778449175,NaN,False,1,0b282_00001,...,0.916667,0.803030,0.874172,0.726689,0.934975,0.928344,53.0,13.0,6.0,66.0
7,0.399825,0.845455,0.324553,0.847826,717,1778446662,NaN,False,1,0b282_00002,...,0.847222,0.848485,0.853147,0.695341,0.935816,0.928350,56.0,10.0,11.0,61.0
8,0.221641,0.890909,0.337888,0.826087,983,1778447471,NaN,False,1,0b282_00003,...,0.791667,0.863636,0.826087,0.655303,0.933712,0.931363,57.0,9.0,15.0,57.0
9,0.179238,0.890909,0.346071,0.840580,1434,1778451365,NaN,False,1,0b282_00004,...,0.875000,0.803030,0.851351,0.680902,0.933502,0.924252,53.0,13.0,9.0,63.0
10,0.289768,0.864865,0.282129,0.884058,542,1778344765,NaN,False,1,0b1e7_00000,...,0.916667,0.848485,0.891892,0.768392,0.949705,0.944041,56.0,10.0,6.0,66.0
11,0.202866,0.927273,0.275658,0.869565,1843,1778348704,NaN,False,1,0b1e7_00001,...,0.833333,0.909091,0.869565,0.742424,0.953072,0.941075,60.0,6.0,12.0,60.0
12,0.218057,0.890909,0.244156,0.891304,2377,1778350340,NaN,False,1,0b1e7_00002,...,0.930556,0.848485,0.899329,0.783588,0.960017,0.957174,56.0,10.0,5.0,67.0
13,0.372050,0.809091,0.276211,0.891304,864,1778345733,NaN,False,1,0b1e7_00003,...,0.916667,0.863636,0.897959,0.782529,0.954335,0.941124,57.0,9.0,6.0,66.0
14,0.260068,0.881818,0.277270,0.855072,896,1778347814,NaN,False,1,0b1e7_00004,...,0.902778,0.803030,0.866667,0.711217,0.952441,0.944328,53.0,13.0,7.0,65.0
15,0.272422,0.882883,0.286847,0.869565,835,1778480636,NaN,False,1,5cb89_00000,...,0.875000,0.863636,0.875000,0.738636,0.948232,0.946343,57.0,9.0,9.0,63.0
16,0.291210,0.881818,0.290091,0.855072,570,1778479836,NaN,False,1,5cb89_00001,...,0.861111,0.848485,0.861111,0.709596,0.946970,0.948965,56.0,10.0,10.0,62.0
17,0.265546,0.900000,0.251750,0.862319,906,1778480851,NaN,False,1,5cb89_00002,...,0.875000,0.848485,0.868965,0.724018,0.962332,0.966262,56.0,10.0,9.0,63.0
18,0.275187,0.881818,0.331226,0.818841,1301,1778482092,NaN,False,1,5cb89_00003,...,0.777778,0.863636,0.817518,0.641887,0.936658,0.937474,57.0,9.0,16.0,56.0
19,0.224470,0.936364,0.332221,0.855072,1516,1778484725,NaN,False,1,5cb89_00004,...,0.861111,0.848485,0.861111,0.709596,0.935185,0.935233,56.0,10.0,10.0,62.0
20,0.271625,0.855856,0.240728,0.920290,1806,1778368698,NaN,False,1,e6410_00000,...,0.888889,0.954545,0.920863,0.842991,0.968013,0.969356,63.0,3.0,8.0,64.0
21,0.317062,0.836364,0.234472,0.920290,1655,1778368215,NaN,False,1,e6410_00001,...,0.902778,0.939394,0.921986,0.841375,0.970118,0.972212,62.0,4.0,7.0,65.0
22,0.288343,0.845455,0.261898,0.905797,907,1778365988,NaN,False,1,e6410_00002,...,0.875000,0.939394,0.906475,0.813966,0.961069,0.960146,62.0,4.0,9.0,63.0
23,0.318620,0.863636,0.233949,0.920290,1276,1778367102,NaN,False,1,e6410_00003,...,0.930556,0.909091,0.924138,0.840266,0.970749,0.973765,60.0,6.0,5.0,67.0
24,0.196012,0.936364,0.264195,0.884058,1836,1778371828,NaN,False,1,e6410_00004,...,0.819444,0.954545,0.880597,0.777268,0.970749,0.974673,63.0,3.0,13.0,59.0
25,0.258182,0.900901,0.262997,0.869565,1111,1778438380,NaN,False,1,f61d8_00000,...,0.902778,0.833333,0.878378,0.739229,0.955387,0.948829,55.0,11.0,7.0,65.0
26,0.222643,0.909091,0.285106,0.869565,1476,1778439458,NaN,False,1,f61d8_00001,...,0.888889,0.848485,0.876712,0.738618,0.951389,0.948169,56.0,10.0,8.0,64.0
27,0.346773,0.845455,0.291049,0.862319,900,1778437737,NaN,False,1,f61d8_00002,...,0.875000,0.848485,0.868965,0.724018,0.947180,0.941808,56.0,10.0,9.0,63.0
28,0.252739,0.890909,0.287904,0.898551,1227,1778438701,NaN,False,1,f61d8_00003,...,0.958333,0.833333,0.907895,0.801164,0.949705,0.941957,55.0,11.0,3.0,69.0
29,0.351279,0.845455,0.292478,0.862319,515,1778439631,NaN,False,1,f61d8_00004,...,0.902778,0.818182,0.872483,0.725168,0.943813,0.931282,54.0,12.0,7.0,65.0
30,0.306295,0.864865,0.272222,0.862319,707,1778497563,NaN,False,1,aa1c4_00000,...,0.902778,0.818182,0.872483,0.725168,0.953493,0.944719,54.0,12.0,7.0,65.0
31,0.221824,0.900000,0.233695,0.898551,2624,1778503354,NaN,False,1,aa1c4_00001,...,0.944444,0.848485,0.906667,0.799006,0.965067,0.958384,56.0,10.0,4.0,68.0
32,0.347391,0.827273,0.288224,0.905797,686,1778497506,NaN,False,1,aa1c4_00002,...,0.930556,0.878788,0.911565,0.811653,0.954125,0.943683,58.0,8.0,5.0,67.0
33,0.249012,0.881818,0.237940,0.913043,2094,1778501720,NaN,False,1,aa1c4_00003,...,0.930556,0.893939,0.917808,0.825887,0.963594,0.956526,59.0,7.0,5.0,67.0
34,0.400336,0.800000,0.304400,0.876812,735,1778500043,NaN,False,1,aa1c4_00004,...,0.902778,0.848485,0.884354,0.753406,0.947180,0.933897,56.0,10.0,7.0,65.0
35,0.336682,0.837838,0.280191,0.891304,1014,1778363406,NaN,False,1,202db_00000,...,0.944444,0.833333,0.900662,0.785334,0.946970,0.931788,55.0,11.0,4.0,68.0
36,0.309474,0.845455,0.295058,0.884058,1880,1778366015,NaN,False,1,202db_00001,...,0.972222,0.787879,0.897436,0.777988,0.943603,0.935195,52.0,14.0,2.0,70.0
37,0.265711,0.918182,0.268354,0.876812,1041,1778363472,NaN,False,1,202db_00002,...,0.930556,0.818182,0.887417,0.756011,0.951389,0.941320,54.0,12.0,5.0,67.0
38,0.268554,0.909091,0.239864,0.905797,863,1778362935,NaN,False,1,202db_00003,...,0.916667,0.893939,0.910345,0.811204,0.959806,0.949796,59.0,7.0,6.0,66.0
39,0.351812,0.818182,0.276136,0.905797,963,1778366196,NaN,False,1,202db_00004,...,0.930556,0.878788,0.911565,0.811653,0.948864,0.938879,58.0,8.0,5.0,67.0
40,0.247368,0.882883,0.327168,0.833333,1038,1778459432,NaN,False,1,90052_00000,...,0.902778,0.757576,0.849673,0.669938,0.937921,0.945715,50.0,16.0,7.0,65.0
41,0.209077,0.909091,0.357296,0.811594,1112,1778459634,NaN,False,1,90052_00001,...,0.888889,0.727273,0.831169,0.626804,0.928451,0.939428,48.0,18.0,8.0,64.0
42,0.311977,0.854545,0.325124,0.862319,1620,1778461166,NaN,False,1,90052_00002,...,0.847222,0.878788,0.865248,0.725324,0.939604,0.947057,58.0,8.0,11.0,61.0
43,0.314442,0.863636,0.332022,0.811594,730,1778458493,NaN,False,1,90052_00003,...,0.875000,0.742424,0.828947,0.624831,0.936448,0.949833,49.0,17.0,9.0,63.0
44,0.187262,0.900000,0.317999,0.862319,1364,1778462924,NaN,False,1,90052_00004,...,0.861111,0.863636,0.867133,0.724367,0.943603,0.953589,57.0,9.0,10.0,62.0
45,0.363331,0.846847,0.264045,0.891304,893,1778349283,NaN,False,1,1d9a4_00000,...,0.916667,0.863636,0.897959,0.782529,0.967172,0.972827,57.0,9.0,6.0,66.0
46,0.350614,0.836364,0.244568,0.927536,692,1778348700,NaN,False,1,1d9a4_00001,...,0.930556,0.924242,0.930556,0.854798,0.974958,0.975888,61.0,5.0,5.0,67.0
47,0.212867,0.909091,0.260135,0.876812,1031,1778349727,NaN,False,1,1d9a4_00002,...,0.916667,0.833333,0.885906,0.754378,0.956439,0.960264,55.0,11.0,6.0,66.0
48,0.206886,0.936364,0.247321,0.869565,2012,1778352643,NaN,False,1,1d9a4_00003,...,0.902778,0.833333,0.878378,0.739229,0.963173,0.967767,55.0,11.0,7.0,65.0
49,0.235125,0.900000,0.274795,0.862319,715,1778351238,NaN,False,1,1d9a4_00004,...,0.888889,0.833333,0.870748,0.724283,0.955598,0.959325,55.0,11.0,8.0,64.0

In [57]:
Overall_outer_ext.to_csv(path+'/results_outer_extended.csv')

In [58]:
Overall_inner_ext = pd.concat([Split0_inner_ext, Split1_inner_ext,
                               Split2_inner_ext, Split3_inner_ext,
                               Split4_inner_ext, Split5_inner_ext,
                               Split6_inner_ext, Split7_inner_ext,
                               Split8_inner_ext, Split9_inner_ext]).reset_index(drop=True)

In [59]:
Overall_inner_ext

,inner_es_loss,inner_es_accuracy,val_loss,val_accuracy,number_epochs,timestamp,checkpoint_dir_name,done,training_iteration,trial_id,...,val_recall,val_specificity,val_f1_score,val_mcc,val_auroc,val_auprc,val_true_positives,val_false_negatives,val_false_positives,val_true_negatives
0,0.425173,0.831461,0.410655,0.818182,9990,1777414509,NaN,False,1,9174c_00089,...,0.894737,0.735849,0.836066,0.640850,0.903343,0.904598,39.0,14.0,6.0,51.0
1,0.394264,0.831461,0.391662,0.863636,4884,1777414282,NaN,False,1,9174c_00079,...,0.912281,0.811321,0.873950,0.729052,0.909964,0.905539,43.0,10.0,5.0,52.0
2,0.403917,0.831461,0.395538,0.845455,9970,1777413551,NaN,False,1,9174c_00084,...,0.912281,0.773585,0.859504,0.694777,0.907977,0.903168,41.0,12.0,5.0,52.0
3,0.486708,0.727273,0.381938,0.783784,9998,1777412403,NaN,False,1,9174c_00120,...,0.810345,0.754717,0.796610,0.566353,0.922902,0.930336,40.0,13.0,11.0,47.0
4,0.583130,0.693182,0.576706,0.738739,4737,1777402203,NaN,False,1,9174c_00125,...,0.896552,0.566038,0.781955,0.493589,0.822707,0.827127,30.0,23.0,6.0,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,0.584412,0.704545,0.501852,0.756757,2029,1778317119,NaN,False,1,83680_00100,...,0.741379,0.773585,0.761062,0.514462,0.860768,0.860780,41.0,12.0,15.0,43.0
1346,0.446403,0.775281,0.523743,0.745455,2214,1778322748,NaN,False,1,83680_00116,...,0.844828,0.634615,0.777778,0.492690,0.822944,0.826116,33.0,19.0,9.0,49.0
1347,0.434155,0.831461,0.421033,0.781818,5484,1778330735,NaN,False,1,83680_00114,...,0.807018,0.754717,0.793103,0.562854,0.898378,0.913355,40.0,13.0,11.0,46.0
1348,0.546042,0.696629,0.581905,0.681818,9985,1778346254,NaN,False,1,83680_00132,...,0.844828,0.500000,0.736842,0.369618,0.759947,0.772498,26.0,26.0,9.0,49.0
1349,0.686535,0.590909,0.659175,0.711712,816,1778325000,NaN,False,1,83680_00125,...,0.810345,0.603774,0.746032,0.424608,0.737801,0.677876,32.0,21.0,11.0,47.0

In [60]:
Overall_inner_ext.to_csv(path+'/results_inner_extended.csv')

In [61]:
Overall_outer_av  = pd.concat([Split0_outer_av, Split1_outer_av,
                               Split2_outer_av, Split3_outer_av,
                               Split4_outer_av, Split5_outer_av,
                               Split6_outer_av, Split7_outer_av,
                               Split8_outer_av, Split9_outer_av]).reset_index(drop=True)

In [62]:
Overall_outer_av

,config/train_loop_config/dataset_test_round,config/train_loop_config/learning_rate,config/train_loop_config/dropout_rate,config/train_loop_config/weight_decay,config/train_loop_config/batch_size,average_outer_es_loss,average_outer_es_accuracy,average_outer_es_precision,average_outer_es_recall,average_outer_es_specificity,...,average_test_recall,average_test_specificity,average_test_f1_score,average_test_mcc,average_test_auroc,average_test_auprc,average_test_true_positives,average_test_false_negatives,average_test_false_positives,average_test_true_negatives
0,0,0.01,0.2,0.0,689,0.280430,0.880164,0.868284,0.909800,0.847605,...,0.938889,0.793939,0.882502,0.744199,0.941709,0.936115,52.4,13.6,4.4,67.6
1,1,0.01,0.2,0.0,689,0.265705,0.882031,0.878225,0.899274,0.863208,...,0.847222,0.830303,0.845490,0.679304,0.934343,0.927976,54.8,11.2,11.0,61.0
2,2,0.01,0.4,0.0,689,0.268562,0.874791,0.854433,0.916455,0.829245,...,0.900000,0.854545,0.885082,0.757630,0.953914,0.945548,56.4,9.6,7.2,64.8
3,3,0.01,0.4,0.0,689,0.265767,0.896577,0.883950,0.923533,0.866909,...,0.850000,0.854545,0.856741,0.704747,0.945875,0.946855,56.4,9.6,10.8,61.2
4,4,0.01,0.2,0.0,689,0.278332,0.867535,0.855205,0.899093,0.832946,...,0.883333,0.939394,0.910812,0.823173,0.968140,0.970030,62.0,4.0,8.4,63.6
5,5,0.01,0.2,0.0,689,0.286323,0.878362,0.864209,0.913309,0.840494,...,0.905556,0.836364,0.880887,0.745640,0.949495,0.942409,55.2,10.8,6.8,65.2
6,6,0.01,0.4,0.0,689,0.304972,0.854791,0.845781,0.885300,0.821263,...,0.922222,0.857576,0.898575,0.783024,0.956692,0.947442,56.6,9.4,5.6,66.4
7,7,0.01,0.4,0.0,689,0.306447,0.865749,0.849107,0.906171,0.821335,...,0.938889,0.842424,0.901485,0.788438,0.950126,0.939396,55.6,10.4,4.4,67.6
8,8,0.01,0.2,0.0,689,0.254025,0.882031,0.865035,0.920085,0.840131,...,0.875000,0.793939,0.848434,0.674253,0.937205,0.947125,52.4,13.6,9.0,63.0
9,9,0.01,0.2,0.0,689,0.273765,0.885733,0.871746,0.916879,0.851669,...,0.911111,0.857576,0.892710,0.771043,0.963468,0.967214,56.6,9.4,6.4,65.6

In [63]:
Overall_outer_av.to_csv(path+'/results_outer_average_over_folds.csv')

In [12]:
# Alternative for Split0-4 and Split5-9
import pandas as pd

path = 'C:/Users/julia/PycharmProjects/gnn-for-ppi/final_results/BRCA/xGAT2MLP'


Split0_4_outer_ext = pd.read_csv(path+'/Split_0-4/results_outer_extended.csv')
Split5_9_outer_ext = pd.read_csv(path+'/Split_5-9/results_outer_extended.csv')

Overall_outer_ext = pd.concat([Split0_4_outer_ext, Split5_9_outer_ext]).reset_index(drop=True)
Overall_outer_ext

,outer_es_loss,outer_es_accuracy,test_loss,test_accuracy,number_epochs,timestamp,checkpoint_dir_name,done,training_iteration,trial_id,...,test_recall,test_specificity,test_f1_score,test_mcc,test_auroc,test_auprc,test_true_positives,test_false_negatives,test_false_positives,test_true_negatives
0,0.269726,0.946429,0.280189,0.913043,128,1777334093,NaN,False,1,1bf90_00000,...,1.000000,0.823529,0.921053,0.838459,0.952101,0.948588,28.0,6.0,0.0,35.0
1,0.269914,0.927273,0.297974,0.869565,241,1777334165,NaN,False,1,1bf90_00001,...,0.942857,0.794118,0.880000,0.746444,0.944538,0.939173,27.0,7.0,2.0,33.0
2,0.266536,0.927273,0.248329,0.898551,214,1777334318,NaN,False,1,1bf90_00002,...,0.971429,0.823529,0.906667,0.805172,0.957983,0.958744,28.0,6.0,1.0,34.0
3,0.272175,0.818182,0.279809,0.884058,219,1777334392,NaN,False,1,1bf90_00003,...,0.942857,0.823529,0.891892,0.772909,0.946219,0.942490,28.0,6.0,2.0,33.0
4,0.251750,0.909091,0.280055,0.884058,195,1777334532,NaN,False,1,1bf90_00004,...,0.942857,0.823529,0.891892,0.772909,0.941176,0.937268,28.0,6.0,2.0,33.0
5,0.223769,0.875000,0.245971,0.884058,272,1777334648,NaN,False,1,1bf90_00005,...,0.897436,0.866667,0.897436,0.764103,0.962393,0.962564,26.0,4.0,4.0,35.0
6,0.286922,0.872727,0.258843,0.913043,157,1777334721,NaN,False,1,1bf90_00006,...,0.948718,0.866667,0.925000,0.823160,0.964957,0.968573,26.0,4.0,2.0,37.0
7,0.405387,0.854545,0.318206,0.898551,65,1777334780,NaN,False,1,1bf90_00007,...,0.897436,0.900000,0.909091,0.794724,0.952991,0.957229,27.0,3.0,4.0,35.0
8,0.205234,0.963636,0.287434,0.855072,331,1777335014,NaN,False,1,1bf90_00008,...,0.820513,0.900000,0.864865,0.714432,0.958974,0.963508,27.0,3.0,7.0,32.0
9,0.233055,0.890909,0.256258,0.913043,370,1777335102,NaN,False,1,1bf90_00009,...,0.948718,0.866667,0.925000,0.823160,0.959829,0.965639,26.0,4.0,2.0,37.0
10,0.360634,0.821429,0.293345,0.913043,126,1777335179,NaN,False,1,1bf90_00010,...,0.944444,0.878788,0.918919,0.826719,0.952862,0.941315,29.0,4.0,2.0,34.0
11,0.243687,0.836364,0.273343,0.913043,197,1777335312,NaN,False,1,1bf90_00011,...,0.944444,0.878788,0.918919,0.826719,0.960438,0.956550,29.0,4.0,2.0,34.0
12,0.217689,0.890909,0.265506,0.927536,440,1777335543,NaN,False,1,1bf90_00012,...,1.000000,0.848485,0.935065,0.863140,0.955387,0.954063,28.0,5.0,0.0,36.0
13,0.348068,0.800000,0.307333,0.898551,83,1777335454,NaN,False,1,1bf90_00013,...,0.944444,0.848485,0.906667,0.799006,0.951178,0.933785,28.0,5.0,2.0,34.0
14,0.157758,0.927273,0.253714,0.913043,567,1777335898,NaN,False,1,1bf90_00014,...,0.944444,0.878788,0.918919,0.826719,0.959596,0.959270,29.0,4.0,2.0,34.0
15,0.259926,0.875000,0.275674,0.826087,192,1777335750,NaN,False,1,1bf90_00015,...,0.780488,0.892857,0.842105,0.661356,0.939024,0.953550,25.0,3.0,9.0,32.0
16,0.235508,0.909091,0.301390,0.811594,387,1777336080,NaN,False,1,1bf90_00016,...,0.804878,0.821429,0.835443,0.618280,0.931185,0.951642,23.0,5.0,8.0,33.0
17,0.298049,0.836364,0.272023,0.855072,210,1777336115,NaN,False,1,1bf90_00017,...,0.853659,0.857143,0.875000,0.704087,0.944251,0.960089,24.0,4.0,6.0,35.0
18,0.300646,0.818182,0.279610,0.869565,111,1777336237,NaN,False,1,1bf90_00018,...,0.853659,0.892857,0.886076,0.736949,0.938153,0.953006,25.0,3.0,6.0,35.0
19,0.236395,0.872727,0.275652,0.826087,154,1777336301,NaN,False,1,1bf90_00019,...,0.804878,0.857143,0.846154,0.651879,0.938153,0.953572,24.0,4.0,8.0,33.0
20,0.277619,0.892857,0.217575,0.869565,236,1777336480,NaN,False,1,1bf90_00020,...,0.870968,0.868421,0.857143,0.737513,0.942275,0.927183,33.0,5.0,4.0,27.0
21,0.274633,0.836364,0.234016,0.855072,292,1777336574,NaN,False,1,1bf90_00021,...,0.838710,0.868421,0.838710,0.707131,0.945671,0.932505,33.0,5.0,5.0,26.0
22,0.310414,0.818182,0.242148,0.869565,155,1777336666,NaN,False,1,1bf90_00022,...,0.870968,0.868421,0.857143,0.737513,0.941426,0.913478,33.0,5.0,4.0,27.0
23,0.268814,0.909091,0.199205,0.869565,196,1777336789,NaN,False,1,1bf90_00023,...,0.870968,0.868421,0.857143,0.737513,0.958404,0.947962,33.0,5.0,4.0,27.0
24,0.197660,0.890909,0.247050,0.826087,291,1777336936,NaN,False,1,1bf90_00024,...,0.741935,0.894737,0.793103,0.648906,0.939728,0.929155,34.0,4.0,8.0,23.0
25,0.258788,0.910714,0.261202,0.869565,406,1769222172,NaN,False,1,a3d2d_00000,...,0.885714,0.852941,0.873239,0.739277,0.946218,0.938878,29.0,5.0,4.0,31.0
26,0.249504,0.890909,0.260677,0.884058,345,1769222145,NaN,False,1,a3d2d_00001,...,0.885714,0.882353,0.885714,0.768067,0.950420,0.944639,30.0,4.0,4.0,31.0
27,0.319704,0.781818,0.268385,0.884058,282,1769222425,NaN,False,1,a3d2d_00002,...,0.828571,0.941176,0.878788,0.773659,0.942857,0.921680,32.0,2.0,6.0,29.0
28,0.191794,0.927273,0.268275,0.884058,470,1769222572,NaN,False,1,a3d2d_00003,...,0.914286,0.852941,0.888889,0.769168,0.942017,0.932009,29.0,5.0,3.0,32.0
29,0.341478,0.872727,0.309593,0.869565,84,1769222572,NaN,False,1,a3d2d_00004,...,0.885714,0.852941,0.873239,0.739277,0.924370,0.863224,29.0,5.0,4.0,31.0
30,0.245307,0.839286,0.235986,0.942029,100,1769222729,NaN,False,1,a3d2d_00005,...,0.969697,0.916667,0.941176,0.885618,0.980640,0.979735,33.0,3.0,1.0,32.0
31,0.244632,0.854545,0.239500,0.913043,100,1769222730,NaN,False,1,a3d2d_00006,...,0.969697,0.861111,0.914286,0.832210,0.984007,0.982668,31.0,5.0,1.0,32.0
32,0.293707,0.890909,0.225603,0.956522,153,1769222922,NaN,False,1,a3d2d_00007,...,1.000000,0.916667,0.956522,0.916667,0.983165,0.981218,33.0,3.0,0.0,33.0
33,0.352669,0.781818,0.216228,0.913043,239,1769223034,NaN,False,1,a3d2d_00009,...,0.909091,0.916667,0.909091,0.825758,0.980640,0.978444,33.0,3.0,3.0,30.0
34,0.293883,0.821429,0.246851,0.942029,209,1769223148,NaN,False,1,a3d2d_00010,...,0.944444,0.939394,0.944444,0.883838,0.964646,0.959986,31.0,2.0,2.0,34.0
35,0.235346,0.854545,0.230491,0.956522,221,1769223272,NaN,False,1,a3d2d_00011,...,0.972222,0.939394,0.958904,0.913155,0.971381,0.970156,31.0,2.0,1.0,35.0
36,0.194819,0.945455,0.246825,0.942029,218,1769223379,NaN,False,1,a3d2d_00012,...,0.972222,0.909091,0.945946,0.885046,0.964646,0.954929,30.0,3.0,1.0,35.0
37,0.249567,0.872727,0.264271,0.913043,272,1769223552,NaN,False,1,a3d2d_00013,...,0.916667,0.909091,0.916667,0.825758,0.962121,0.958921,30.0,3.0,3.0,33.0
38,0.363058,0.781818,0.244824,0.927536,91,1769223534,NaN,False,1,a3d2d_00014,...,0.944444,0.909091,0.931507,0.854976,0.956229,0.926715,30.0,3.0,2.0,34.0
39,0.234799,0.821429,0.309552,0.811594,198,1769223751,NaN,False,1,a3d2d_00015,...,0.842105,0.774193,0.831169,0.618402,0.926146,0.948662,24.0,7.0,6.0,32.0
40,0.223413,0.909091,0.286363,0.840580,325,1769223851,NaN,False,1,a3d2d_00016,...,0.894737,0.774193,0.860760,0.677614,0.948217,0.963339,24.0,7.0,4.0,34.0
41,0.270649,0.836364,0.293541,0.840580,255,1769224018,NaN,False,1,a3d2d_00017,...,0.842105,0.838710,0.853333,0.679088,0.931239,0.950192,26.0,5.0,6.0,32.0
42,0.341150,0.818182,0.300707,0.811594,231,1769224098,NaN,False,1,a3d2d_00018,...,0.894737,0.709677,0.839506,0.620421,0.933786,0.954123,22.0,9.0,4.0,34.0
43,0.245075,0.909091,0.325499,0.840580,548,1769224463,NaN,False,1,a3d2d_00019,...,0.842105,0.838710,0.853333,0.679088,0.932088,0.949202,26.0,5.0,6.0,32.0
44,0.319889,0.839286,0.211486,0.898551,221,1769224334,NaN,False,1,a3d2d_00020,...,0.921053,0.870968,0.909091,0.794724,0.971986,0.977009,27.0,4.0,3.0,35.0
45,0.307140,0.854545,0.197431,0.913043,200,1769224560,NaN,False,1,a3d2d_00021,...,0.947368,0.870968,0.923077,0.824661,0.983871,0.987305,27.0,4.0,2.0,36.0
46,0.222485,0.854545,0.207356,0.927536,229,1769224706,NaN,False,1,a3d2d_00022,...,0.947368,0.903226,0.935065,0.853497,0.987267,0.989865,28.0,3.0,2.0,36.0
47,0.220591,0.909091,0.217559,0.913043,189,1769224776,NaN,False,1,a3d2d_00023,...,0.921053,0.903226,0.921053,0.824278,0.977929,0.981838,28.0,3.0,3.0,35.0
48,0.240687,0.909091,0.230429,0.898551,275,1769224968,NaN,False,1,a3d2d_00024,...,0.894737,0.903226,0.906667,0.795938,0.966044,0.970279,28.0,3.0,4.0,34.0
49,0.299559,0.890909,0.197018,0.956522,245,1769225023,NaN,False,1,a3d2d_00008,...,1.000000,0.916667,0.956522,0.916667,0.991582,0.990952,33.0,3.0,0.0,33.0

In [13]:
Overall_outer_ext.to_csv('C:/Users/julia/PycharmProjects/gnn-for-ppi/final_results/BRCA/xGAT2MLP/results_outer_extended.csv')